//
//  Strings.swift
//  InputValidation
//
//  Created by Richard Burgess on 10/30/25.
//

import Foundation

// autogenerated in XCode 26
#if swift(<6.2)
extension LocalizedStringResource {
    static let firstName: LocalizedStringResource = "firstName"
    static let lastName: LocalizedStringResource = "lastName"
    static func emptyStringError(fieldName: String) -> LocalizedStringResource {
        "\(fieldName) must not be empty"
    }
    static func maxStringLengthError(fieldName: String, maxLength: Int) -> LocalizedStringResource {
        "\(fieldName) must be less than \(maxLength)"
    }
    static let password: LocalizedStringResource = "password"
    static let passwordError: LocalizedStringResource = "passwordError"
    static let confirmPassword: LocalizedStringResource = "confirmPassword"
    static let confirmPasswordError: LocalizedStringResource = "confirmPasswordError"
    static let cvc: LocalizedStringResource = "cvc"
    static let cvcError: LocalizedStringResource = "cvcError"
    static let creditCardNumber: LocalizedStringResource = "creditCardNumber"
    static let creditCardError: LocalizedStringResource = "creditCardError"
    static let expirationDate: LocalizedStringResource = "expirationDate"
    static let expirationDateRequired: LocalizedStringResource = "expirationDateRequired"
    static let expired: LocalizedStringResource = "expired"
}
#endif
